# Generated by Django 3.1.7 on 2021-04-18 20:07

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210418_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmovie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.new_movie_save),
        ),
    ]
